services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    hostname: '192.168.21.2' # 替换为你的域名或 IP
    environment:
      GITLAB_ROOT_PASSWORD: 'xinxinxin' # 替换为管理员密码
      GITLAB_ROOT_EMAIL: 'admin@xin.com'     # 可选：替换为管理员邮箱
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    restart: always

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
